### PR TITLE
Improve markdown of docker readme.md

### PR DESCRIPTION
**Pull request by drfenixion**
Improve markdown of docker readme.md

### CODE REVIEW

**Review by galou — APPROVED** [review]
Thanks!

**Comment by galou** [comment]
Can you solve the conflicts so that I can merge?

**Comment by drfenixion** [comment]
> Can you solve the conflicts so that I can merge?

I solved conflict after adding PR via web interface. I should be ok.

"This branch has no conflicts with the base branch"

**Comment by galou** [comment]
Maybe you didn't push because there is still a conflict?

**Pull request closed without merging**
