### PR TITLE
Replace some icons with better associated. Icons created by me.

### PR DESCRIPTION
**Pull request by drfenixion**
freecad_cross_replace_icons
Marked NEW icons.

freecad_cross_replace_old_icons
Marked OLD icons.

[replace some icons with better associated. Icons created by me.](https://github.com/galou/freecad.cross/pull/10/commits/b78641f434f0fb911a66524b5c9335dd9f8664e9)

### CODE REVIEW

**Comment by drfenixion** [comment]
@galou, Hi, you dont like my icons or something other reason not merge? 
Old icons pretty similar to each other and dont do association to robot, link, joint. It is reason of new icons.

**Comment by galou** [comment]
@drfenixion I was waiting for other people to react on this. The idea behind the original icons is that they are based on the ROS nine-dot logo. I understood your remark about the difficult distinction between icons and redesigned them to make it more clear that robots are represented by an "R", joints by a "J", ... and render the link to the nine-dot icon more clear. Please tell me your opinion.

**Comment by drfenixion** [comment]
@galou , 

> robots are represented by an "R", joints by a "J"

Ah, i did not even know that at start. Because the brain expects an association not with a letter, but with an entity.

My opinion is icons should be very simple and well associated with entity they represent. Also they should be easy to distinguish each other.

**Comment by galou** [comment]
Let's wait for others to react.

**Pull request closed without merging**
