### PR TITLE
fix Set Placement with Link and one LCS

### PR DESCRIPTION
**Pull request by sprhawk**
fix Set Placement:

Select one Link and LCS and other

### CODE REVIEW

**Comment by sprhawk** [comment]
Should this change be `MountedPlacement` or `Placement` ?

**Comment by galou** [comment]
`MountedPlacement` is a fixed property of a link whereas `Placement` is the placement relative to the robot and gets recalculated e.g. when the joint values are changed in the robot.

Can you give an minimal example to test your change. Please, at best, in Python code. You can generate Python code with [ObjectsToPython.FCMacro](https://github.com/FreeCAD/FreeCAD-macros/blob/master/ImportExport/ObjectsToPython.FCMacro).

**Comment by sprhawk** [comment]
> `MountedPlacement` is a fixed property of a link whereas `Placement` is the placement relative to the robot and gets recalculated e.g. when the joint values are changed in the robot.
> 
> Can you give an minimal example to test your change. Please, at best, in Python code. You can generate Python code with [ObjectsToPython.FCMacro](https://github.com/FreeCAD/FreeCAD-macros/blob/master/ImportExport/ObjectsToPython.FCMacro).

Actually I'm not sure it should be changed, but in original code, when I `Set Placement`, it didn't change link's placement.

**Comment by drfenixion** [comment]
I dont think it should be changed because tool works as expected. Just usage of tool is sophisticated.
You can check my tips for this tool and also doc.

https://github.com/galou/freecad.cross/issues/32#issuecomment-2002927203
https://github.com/galou/freecad.cross/wiki/Command-SetPlacement

**Pull request closed without merging**
