### PR TITLE
Minor typing changes and review

### PR DESCRIPTION
**Pull request by mnesarco**
Path manipulations in this module (ros.utils) looks very Linux specific. There may be portability issues?

### CODE REVIEW

**Comment by mnesarco** [comment]
Typing syntax: using squared brackets to enclose typing is only valid to pass type parameters, so:

```python
myvar: [T1 | T2]  # Bad type hint

myvar: T1 | T1        # Good type hint
mylst: list[T1 | T2]  # Good type hint
```

**Comment by mnesarco** [comment]
https://github.com/galou/freecad.cross/issues/53

**Review by galou — APPROVED** [review]
Thanks!

**Comment by galou** [comment]
They are for sure some compatibility issues for other OS than Linux but PRs to solve this are welcome. The framework this workbench is meant for ([ROS](https://ros.org)) is also hardly compatible with Windows and I don't know with MacOS.

I guess, I should work on the configuration of my editor (Neovim) because it keeps bothering me about lines having more than 80 characters, whereas I'd like to use 90 but it doesn't warn me about errors in typing hints, which probably means that it doesn't do any static type checking.

**Comment by mnesarco** [comment]
@galou I suggest you to use ruff: https://docs.astral.sh/ruff/

**Pull request merged**
